### PR TITLE
Model name fix

### LINKED ISSUE #16: model_name is defined by Active Record
ActiveRecord::DangerousAttributeError: model_name is defined by Active Record. Check to make sure that you don't have an attribute or method with the same name.

### PR DESCRIPTION
**Pull request by celsodantas**
@christiannaths @eduard-io @adslyw want to code review this?
Should fix #16 

I'm just renaming the `model_name` to `counter_model_name` (I'm open for suggestions for a better name).

Will stop this error:

```
ActiveRecord::DangerousAttributeError: model_name is defined by Active Record. Check to make sure that you don't have an attribute or method with the same name.
```

### CODE REVIEW

**Comment by eduard-io** [comment]
Looks good. What about people that are already using the Gem? They'll need to migrate the tables too, a notice after the updating the gem would be useful.

**Comment by celsodantas** [comment]
Any idea how to add the notice after gem update? 
I'm pretty sure that bundle swallows these: http://guides.rubygems.org/specification-reference/#post_install_message

I might just bump the major version and add an announcement in the readme.

**Comment by eduard-io** [comment]
I'm not sure about bundle swallowing the `post_install_message`, the [globalize gem](https://github.com/globalize/globalize/blob/master/globalize.gemspec#L40-L53) uses them and I've seen the message.

**Comment by celsodantas** [comment]
True, it works.

But there's no specific messages for updates to version X. I wouldn't want to keep a message to migrate the database even for fresh install, and also I'll need to keep the msg around forever.

Better ideas? I think that bumping the major version is enough. I'd release a `1.0.0`.

**Comment by celsodantas** [comment]
well, I'll release a `1.0.0` version to let people know about the API break

**Pull request merged**
