### PR TITLE
ruby 2.7 literal strings fix

### PR DESCRIPTION
**Pull request by andre-lgf**
Fixes for Ruby 2.7

### CODE REVIEW

**Comment by celsodantas** [comment]
Thanks for the contribution. Get CI green and I'll merge it. =)

**Comment by christiannaths** [comment]
@celsodantas So it looks like that failing CI run triggered this: https://github.com/rails/rails/issues/38972

I ran the tests locally against ruby 2.2.4 (which resolved Rails to 5.2.6.2) and they passed. Maybe just re-run that build?

**Comment by christiannaths** [comment]
@celsodantas I thought I'd try to re-trigger the build, but I don't think it worked. I don't have insight as to why it's not re-running, but I've been using this fork in a Ruby 3.1 / Rails 7 app and it's 💯 

You ok if I merge this? Tests are all green when I run them locally against Rubies `2.2.4`, `2.3.0`, and `~> 2.7`, and `~> 3.1`

**Comment by christiannaths** [comment]
@celsodantas No worries at all! Thanks for circling back to it. What would it take to do a new version release to rubygems?

**Comment by celsodantas** [comment]
I'll do it later today! =D

**Pull request merged**
